project:
  type: website

website:
  title: "Home"
  open-graph: true  # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    title: Ainhoa Agirrebengoa
    right:
      - href: talks.qmd
        text: Speaking
        icon: megaphone
      - href: blog.qmd
        text: Blog
    tools:
      - icon: github
        href: github.com/ainhoaa14

format:
  html:
    fontcolor: "darkgreen"
    backgroundcolor: "#eaffe3"
    theme: [cosmo, styles.scss]


